-- from https://github.com/LunarVim/LunarVim/blob/407e7b05eace59f571730f7d1467c39f7ba73a90/lua/lvim/icons.lua
-- https://www.nerdfonts.com/cheat-sheet
return {
  kind = {
    Text = "󰉿",
    Method = "m",
    Function = "󰊕",
    Array = "",
    Boolean = "",
    Constructor = "", -- 
    Field = "", -- 
    Variable = "󰆧",  -- 
    Class = "󰌗",
    Interface = "",  -- 
    Module = "",  -- 
    Namespace = "",
    Key = "",
    Property = "",  -- 
    Unit = "",  -- 
    Value = "󰎠",  -- 
    Enum = "", -- 
    Keyword = "󰌋",
    Number = "",
    Snippet = "",
    Object = "",
    Null = "󰟢",
    Color = "󰏘", -- 
    File = "󰈙",  -- 
    Reference = "", -- 
    Folder = "󰉋",
    EnumMember = "", -- 
    String = "",
    Constant = "󰇽", -- 
    Struct = "",  -- 
    Event = "",  -- 
    Operator = "󰆕", -- 
    TypeParameter = "󰊄",  -- 
    Package = "",
    Codeium = "󰚩",
    Copilot = "",
  },
  git = {
    LineAdded = "",
    LineModified = "",
    LineRemoved = "",
    FileDeleted = "",
    FileIgnored = "◌",
    FileRenamed = "",
    FileStaged = "S",
    FileUnmerged = "",
    FileUnstaged = "",
    FileUntracked = "U",
    Diff = "",
    Repo = "",
    Octoface = "",
    Branch = "",
  },
  ui = {
    ArrowCircleDown = "",
    ArrowCircleLeft = "",
    ArrowCircleRight = "",
    ArrowCircleUp = "",
    BoldArrowDown = "",
    BoldArrowLeft = "",
    BoldArrowRight = "",
    BoldArrowUp = "",
    BoldClose = "",
    BoldDividerLeft = "",
    BoldDividerRight = "",
    BoldLineLeft = "▎",
    BookMark = "",
    BoxChecked = "",
    Bug = "",
    Stacks = "",
    Scopes = "",
    Watches = "󰂥",
    DebugConsole = "",
    Calendar = "",
    Check = "",
    ChevronRight = "",
    ChevronShortDown = "",
    ChevronShortLeft = "",
    ChevronShortRight = "",
    ChevronShortUp = "",
    Circle = "",
    Close = "󰅖",
    CloudDownload = "",
    Code = "",
    Comment = "",
    Dashboard = "",
    DividerLeft = "",
    DividerRight = "",
    DoubleChevronRight = "»",
    Ellipsis = "",
    EmptyFolder = "",
    EmptyFolderOpen = "",
    File = "",
    FileSymlink = "",
    Files = "",
    FindFile = "󰈞",
    FindText = "󰊄",
    Fire = "",
    Folder = "󰉋",
    FolderOpen = "",
    FolderSymlink = "",
    Forward = "",
    Gear = "",
    History = "",
    Lightbulb = "",
    LineLeft = "▏",
    LineMiddle = "│",
    List = "",
    Lock = "",
    NewFile = "",
    Note = "",
    Package = "",
    Pencil = "󰏫",
    Plus = "",
    Project = "",
    Search = "",
    SignIn = "",
    SignOut = "",
    Tab = "󰌒",
    Table = "",
    Target = "󰀘",
    Telescope = "",
    Text = "",
    Tree = "",
    Triangle = "󰐊",
    TriangleShortArrowDown = "",
    TriangleShortArrowLeft = "",
    TriangleShortArrowRight = "",
    TriangleShortArrowUp = "",
  },
  diagnostics = {
    Prefix = "●",   -- Could be '●', '■', '▎', 'x'
    BoldError = "",
    Error = "",
    BoldWarning = "",
    Warning = "",
    BoldInformation = "",
    Information = "",
    BoldQuestion = "",
    Question = "",
    BoldHint = "",
    Hint = "󰌶",
    Debug = "",
    Trace = "✎",
    Reject = "",
    stoped = "󰁕",
  },
  misc = {
    Robot = "󰚩",
    Squirrel = "",
    Tag = "",
    Watch = "",
    Smiley = "",
    Package = "",
    CircuitBoard = "",
    Bugs = "",
    Bugs1 = "",
  },
  localsigns = {
    Error = "✘", -- ×
    Warn = "",  -- ▲
    Hint = "󰌶",  -- ⚑
    Info = ""   --  ◉ »
  },
}
