#!/bin/sh

# Bundler for non-Ruby dependencies from Homebrew, Homebrew Cask, Mac App Store
# and Whalebrew.

# brew bundle [install]:
#     Install and upgrade (by default) all dependencies from the Brewfile.

# You can specify the Brewfile location using --file or by setting the
# HOMEBREW_BUNDLE_FILE environment variable.

# You can skip the installation of dependencies by adding space-separated values
# to one or more of the following environment variables:
# HOMEBREW_BUNDLE_BREW_SKIP, HOMEBREW_BUNDLE_CASK_SKIP,
# HOMEBREW_BUNDLE_MAS_SKIP, HOMEBREW_BUNDLE_WHALEBREW_SKIP,
# HOMEBREW_BUNDLE_TAP_SKIP.

# brew bundle will output a Brewfile.lock.json in the same directory as the
# Brewfile if all dependencies are installed successfully. This contains
# dependency and system status information which can be useful in debugging brew
# bundle failures and replicating a "last known good build" state. You can
# opt-out of this behaviour by setting the HOMEBREW_BUNDLE_NO_LOCK environment
# variable or passing the --no-lock option. You may wish to check this file into
# the same version control system as your Brewfile (or ensure your version
# control system ignores it if you'd prefer to rely on debugging information from
# a local machine).

# brew bundle dump:
#     Write all installed casks/formulae/images/taps into a Brewfile in the
# current directory.

# brew bundle list:
#     List all dependencies present in the Brewfile.

# creates Brewfile in the current directory from currently-installed packages
brew bundle dump

# edit Brewfile

# install everything from the Brewfile
# brew bundle


